# Generated by Django 4.2.11 on 2024-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0002_alter_routine_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='shift',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
