# Generated by Django 4.2.14 on 2024-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0004_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='active',
            field=models.CharField(choices=[('CLASSDAY', 'CLASSDAY'), ('HOLIDAY', 'HOLIDAY'), ('EXAMS', 'EXAMS')], default='CLASSDAY'),
        ),
    ]
