# Generated by Django 4.2.14 on 2024-08-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0005_alter_classes_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classes',
        ),
    ]
