# Generated by Django 4.2.14 on 2024-08-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0007_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='active',
            new_name='class_state',
        ),
    ]
