# Generated by Django 4.2.14 on 2024-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0008_rename_active_classes_class_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_state',
            field=models.CharField(choices=[('CLASSDAY', 'CLASSDAY'), ('HOLIDAY', 'HOLIDAY'), ('EXAMS', 'EXAMS')]),
        ),
    ]
