# Generated by Django 4.2.14 on 2024-10-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0009_alter_classes_class_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='section',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1'),
            preserve_default=False,
        ),
    ]
