# Generated by Django 4.2.14 on 2024-10-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0010_routine_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
