# Generated by Django 4.2.14 on 2024-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0012_alter_routine_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='time',
            new_name='stime',
        ),
        migrations.AddField(
            model_name='routine',
            name='etime',
            field=models.TimeField(default='7:0:0'),
        ),
    ]
