# Generated by Django 4.2.14 on 2024-10-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0016_alter_routine_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='shift',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
